version: '2'
services:
    constructmanagerapi-app:
        image: constructmanagerapi
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://constructmanagerapi-mariadb:3306/constructmanagerapi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    constructmanagerapi-mariadb:
        extends:
            file: mariadb.yml
            service: constructmanagerapi-mariadb
